finishing translate for day5 pt-br
MichaelCade/90DaysOfDevOps pull request #454
Opened 2023-10-17 19:36 UTC by iamabrantes

2023-10-19 08:28 UTC, juliafmorgado requested changes
Thanks for your contribution Jonathan!

I've made a few suggestions to improve the readability of the text :)

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Este é efetivamente o resultado das fases de Entrega Contínua acima, mais o resultado da fase de Lançamento(Release). Esse é o caso tanto do fracasso quanto do sucesso, mas isso é realimentado na ent
"Isso é efetivamente o resultado das fases de Entrega Contínua acima, juntamente com o resultado da fase de Lançamento (Release). Isso se aplica tanto em caso de falha quanto de sucesso, mas essas informações são realimentadas na Entrega Contínua ou movidas para a Implantação Contínua."

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Entrega Contínua = Planejar > Codar > Construir > Testar
I would suggest using Nouns instead of Verbs:
"Entrega Contínua = Planejamento > Codificação > Construção > Teste"

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Integração Contínua = Plano > Código > Construir > Teste > Lançamento(Release)
Try to maintain consistency (whether use verbs or nouns):
"Integração Contínua = Planejamento > Codificação > Construção > Teste > Lançamento (Release)"

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +### Implantação Contínua
"Implantação Contínua (Continuous Deployment)"

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Se você tiver uma versão bem-sucedida de sua integração contínua, mude para a implantação contínua, que traz as seguintes fases
I would suggest capitalizing the terms CI/CD:
"Se você tiver uma versão bem-sucedida de sua Integração Contínua, avance para a Implantação Contínua, que inclui as seguintes fases"

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +O lançamento(release) da Integração Contínua foi bem-sucedida = Implantação Contínua = Implantar > Operar > Monitorar
"Lançamento (Release) da Integração Contínua bem sucedido = Implantação Contínua = Implantação > Operação > Monitoramento"

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Você pode ver essas três noções Contínuas acima como uma simples coleção de fases do ciclo de vida do DevOps.
Capitalize the term _DevOps Lifecycle_:
"Você pode ver essas três noções contínuas acima como a simples coleção de fases do Ciclo de Vida DevOps."

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Esta última parte foi uma recapitulação para mim no Dia 3, mas acho que isso torna as coisas mais claras para mim.
"Esta última parte foi uma recapitulação do Dia 3 para mim, mas acho que isso torna as coisas mais claras para mim.

2023-10-19 08:28 UTC, juliafmorgado commented on 2022/pt-br/Days/day05.md
> +Se você chegou até aqui, saberá se é aqui que deseja estar ou não.
Obs: In the previous days the translation was "Se você chegou até aqui, saberá se é aqui que você quer estar ou não. Vejo você no Dia 5."
I think "deseja" is more appropriate so let's keep it like that moving forward.

2023-10-19 14:13 UTC, iamabrantes commented
Correções efetuadas.

2023-10-24 12:04 UTC, juliafmorgado commented
/lgtm

2024-01-04 17:44 UTC, merged